let name = "guru nanak institute of TECHNOLOGY";
console.log('upper case:',name.toUpperCase());
console.log('lower case:',name.toLowerCase());
console.log('character at position 8 is ',name.charAt(8));
console.log('starting index of technology is ',name.indexOf('technology'));
console.log('concatination:',name.concat('bidar'));
console.log('includes:',name.includes('guru',0));
console.log('replace TECHNOLOGY by technology ',name.replace('TECHNOLOGY','technology'));
console.log('spliting:',name.split(" "));
console.log('substring:',name.substr(3,8));
console.log('search',name.search('of'));
console.log("**********************************");
let name1 = "pooja is good girl";
console.log('upper case:',name1.toUpperCase());
console.log('lower case:',name1.toLowerCase());
console.log('character at position 8 is ',name1.charAt(8));
console.log('starting index of M is ',name1.indexOf('p'));
console.log('concatination:',name1.concat('and inocent'));
console.log('includes:',name1.includes('pooja',0));
console.log('replace:',name1.replace('p','P'));
console.log('spliting:',name1.split("."));
console.log('substring:',name1.substr(3,8));
console.log('search',name1.search('oo'));
console.log("**********************************");
let name2 = "jai shivray";
console.log('upper case:',name2.toUpperCase());
console.log('lower case:',name2.toLowerCase());
console.log('character at position 8 is ',name2.charAt(5));
console.log('starting index of PU is ',name2.indexOf('ai'));
console.log('concatination:',name2.concat('maharastra'));
console.log('includes:',name2.includes('shi',0));
console.log('replace: ',name2.replace('jai','JAI'));
console.log('spliting:',name2.split(" "));
console.log('substring:',name2.substr(3,5));
console.log('search',name2.search('pu'));
console.log("**********************************");


let name8 = "Bhagya";
console.log('upper case:',name8.toUpperCase());
console.log('lower case:',name8.toLowerCase());
console.log('character at position 8 is ',name8.charAt(8));
console.log('starting index :',name8.indexOf('ya'));
console.log('concatination:',name8.concat(' Suresh'));
console.log('includes:',name8.includes('ya',0));
console.log('replace:',name8.replace('B','b'));
console.log('spliting:',name8.split("a"));
console.log('substring:',name8.substr(3,8));
console.log('search',name8.search('ya'));
console.log("**********************************");

let name3 = "pooja bhujange";
console.log('upper case:',name3.toUpperCase());
console.log('lower case:',name3.toLowerCase());
console.log('character at position 8 is ',name3.charAt(8));
console.log('starting index:',name3.indexOf('j'));
console.log('concatination:',name3.concat('  anilkumar'));
console.log('includes:',name3.includes('bhuj',0));
console.log('replace: ',name3.replace('p','P'));
console.log('spliting:',name3.split("u"));
console.log('substring:',name3.substr(3,8));
console.log('search',name3.search('a'));
console.log("**********************************");
let name4 = "Sachin biradar";
console.log('upper case:',name4.toUpperCase());
console.log('lower case:',name4.toLowerCase());
console.log('character at position 8 is ',name4.charAt(8));
console.log('starting index:',name4.indexOf('a'));
console.log('concatination:',name4.concat(' dilip rao'));
console.log('includes:',name4.includes('sach',0));
console.log('replace: ',name.replace('S','s'));
console.log('spliting:',name.split(" "));
console.log('substring:',name.substr(3,8));
console.log('search',name.search('bira'));
console.log("**********************************");
let name5 = "prabhavti";
console.log('upper case:',name5.toUpperCase());
console.log('lower case:',name5.toLowerCase());
console.log('character at position 8 is ',name5.charAt(8));
console.log('starting index:',name5.indexOf('bhav'));
console.log('concatination:',name5.concat(' bhujange'));
console.log('includes:',name5.includes('vati',0));
console.log('replace :',name.replace('p','P'));
console.log('spliting:',name.split(" "));
console.log('substring:',name.substr(3,8));
console.log('search',name.search('ti'));
console.log("**********************************");
let name6 = "Om narendra nathaya ";
console.log('upper case:',name6.toUpperCase());
console.log('lower case:',name6.toLowerCase());
console.log('character at position 8 is ',name6.charAt(8));
console.log('starting index :',name6.indexOf('n'));
console.log('concatination:',name6.concat(' nam'));
console.log('includes:',name6.includes('nare',0));
console.log('replace:',name6.replace('O','o'));
console.log('spliting:',name6.split(" "));
console.log('substring:',name6.substr(3,8));
console.log('search',name6.search('nath'));
console.log("**********************************");
let name7 = "Suresh";
console.log('upper case:',name7.toUpperCase());
console.log('lower case:',name7.toLowerCase());
console.log('character at position 8 is ',name7.charAt(8));
console.log('starting index :',name7.indexOf('sh'));
console.log('concatination:',name7.concat(' chikke Gowda'));
console.log('includes:',name7.includes('sh',0));
console.log('replace: ',name.replace('S','s'));
console.log('spliting:',name.split("h"));
console.log('substring:',name.substr(3,8));
console.log('search',name.search('sh'));
console.log("**********************************");

let name9 = "yogesh";
console.log('upper case:',name9.toUpperCase());
console.log('lower case:',name9.toLowerCase());
console.log('character at position 4 is ',name9.charAt(4));
console.log('starting index:',name9.indexOf('sh'));
console.log('concatination:',name9.concat(' bhujange'));
console.log('includes:',name9.includes('bh',0));
console.log('replace: ',name9.replace('y','Y'));
console.log('spliting:',name9.split("s"));
console.log('substring:',name9.substr(3,8));
console.log('search',name9.search('sh'));
console.log("**********************************");
