console.log('========================================')
const falls=['shivanasamudra','Abbey','Iruppu','jog']
console.log(Array.isArray(falls))
console.log(falls.includes('Iruppu',2))
console.log(falls.push('hogenakal','Balmuri'))
console.log(falls.pop())
console.log(falls)
console.log(falls.unshift('gaganachukki'))
console.log(falls)
falls.shift()
console.log(falls)
const falls1=falls.splice(2,2,'unchali')
console.log(falls1)
console.log(falls)
const falls2=falls.slice(1,3)
console.log(falls2)
const falls3=falls.join('_')
console.log(falls3)
console.log(falls.indexOf('Abbey',2))
falls.map(function(value,index){
    console.log(falls[index],index)
})
falls.filter(function(val,ind){
    console.log(ind)
})
console.log('========================================')
const metals=['copper','silver','iron']
console.log(Array.isArray(metals))
console.log(metals.includes('silver',2))
metals.push('gold')
console.log(metals)
metals.pop()
console.log(metals)
metals.unshift('zinc','aluminium')
console.log(metals)
metals.shift()
console.log(metals)
metals.splice(3,1)
console.log(metals)
const meta=metals.slice(1,2)
console.log(meta)
const meta1=metals.join('+')
console.log(meta1)
console.log(metals.indexOf('silver',1))
console.log('========================================')
const sports=['vollyball','basket ball','base ball','aerobics']
console.log(Array.isArray(sports))
console.log(sports.includes('basket ball',1))
sports.push('athletics')
console.log(sports)
sports.pop()
console.log(sports)
sports.unshift('kabbadi')
console.log(sports)
sports.shift()
console.log(sports)
sports.splice(1,2,'kho-kho')
console.log(sports)
const spo1=sports.slice(2,3)
console.log(spo1)
const spo2=sports.join('1')
console.log(spo2)
const spo3=sports.indexOf('aerobics',2)
console.log(spo3)
console.log('========================================')
const fruits=['green apple','strawberry','chikkus']
console.log(Array.isArray(fruits))
console.log(fruits.includes('chikkus',3))
console.log(fruits.push('banana'))
fruits.pop()
console.log(fruits)
fruits.unshift('pomogranate','mango')
console.log(fruits)
fruits.shift()
console.log(fruits)
fruits.splice(2,1,'kiwi')
console.log(fruits)
const fru1=fruits.slice(0,2)
console.log(fru1)
const fru2=fruits.join('#')
console.log(fru2)
console.log(fruits.indexOf('chikkus',2))
console.log('========================================')
const trees=['neem','peepal','amla','banyan']
console.log(Array.isArray(trees))
console.log(trees.includes('amla',1))
console.log(trees.push('aloe vera'))
trees.pop()
console.log(trees)
trees.unshift('tulasi')
console.log(trees)
trees.shift()
console.log(trees)
trees.splice(2,1,'tulasi')
console.log(trees)
const tree1=trees.slice(0,2)
console.log(tree1)
const tree2=trees.join('@')
console.log(tree2)
console.log(trees.indexOf('peepal',3))
console.log('========================================')
const insects=['bee','dragonfly','spider']
console.log(Array.isArray(insects))
console.log(insects.includes('spider',1))
console.log(insects.push('ant'))
insects.pop()
console.log(insects)
insects.unshift('caterpillar')
console.log(insects)
insects.shift()
console.log(insects)
insects.splice(0,2,'caterpillar')
console.log( insects)
const ins1=insects.slice(0,1)
console.log(ins1)
const ins2=insects.join('$')
console.log(ins2)
console.log(insects.indexOf('caterpillar',0))
console.log('========================================')
const scientist=['marie curie','thomas','pasture']
console.log(Array.isArray(scientist))
console.log(scientist.includes('pasture',3))
console.log(scientist.push('faraday'))
scientist.pop()
console.log(scientist)
scientist.unshift('faraday')
console.log(scientist)
scientist.shift()
console.log(scientist)
scientist.splice(1,2,'faraday')
console.log(scientist)
const sci1=scientist.slice(0,1)
console.log(sci1)
const sci2=scientist.join('&')
console.log(sci2)
console.log(scientist.indexOf('faraday',1))
console.log('========================================')
const fever=['dengue','viral']
console.log(Array.isArray(fever))
console.log(fever.includes('dengue',0))
console.log(fever.push('lassa','jaundice'))
fever.pop()
console.log(fever)
fever.unshift('jaundice')
console.log(fever)
fever.shift()
console.log(fever)
fever.splice(1,1,'jaundice')
console.log(fever)
const fev1=fever.slice(0,2)
console.log(fev1)
const fev2=fever.join('^')
console.log(fev2)
console.log(fever.indexOf('dengue',0))
console.log('========================================')
const continent=['asia','africa','europe']
console.log(Array.isArray(continent))
console.log(continent.includes('africa',0))
console.log(continent.push('antartica'))
continent.pop()
console.log(continent)
continent.unshift('antartica')
console.log(continent)
continent.shift()
console.log(continent)
continent.splice(1,2,'antartica')
console.log(continent)
const con1=continent.slice(1,2)
console.log(con1)
const con2=continent.join('*')
console.log(con2)
console.log(continent.indexOf('africa',0))
console.log('========================================')
const desert=['sahara','namib','mojave']
console.log(Array.isArray(desert))
console.log(desert.includes('mojave',1))
console.log(desert.push('gobi'))
desert.pop()
console.log(desert)
desert.unshift('gobi')
console.log(desert)
desert.shift()
console.log(desert)
desert.splice(0,1,'gobi')
console.log(desert)
const des1=desert.slice(1,3)
console.log(des1)
const des2=desert.join('!')
console.log(des2)
console.log(desert.indexOf('namib',1))

console.log('========================================')


