let wonders='Effil Tower'
console.log(wonders.toLowerCase())
console.log(wonders.toUpperCase())
console.log(wonders.charAt(3))
console.log(wonders.indexOf('ow',4))
console.log(wonders.concat(' paris'))
console.log(wonders.includes('fi',0))
console.log(wonders.replace('er','s'))
console.log(wonders.split('i',2))
console.log(wonders.substr(3,6))
console.log(wonders.search('fil'))
console.log(wonders.trim())
console.log('=============================')
let element='Neptunium'
console.log(element.toLowerCase())
console.log(element.toUpperCase())
console.log(element.charAt(5))
console.log(element.indexOf('uni',4))
console.log(element.concat('carbon'))
console.log(element.includes('pt',5))
console.log(element.replace('iu','dd'))
console.log(element.split('u',1))
console.log(element.substr(4,6))
console.log(element.search('ccc'))
console.log(element.trim())
console.log('=============================')
let str='Gandhi jayanthi'
console.log(str.toLowerCase())
console.log(str.toUpperCase())
console.log(str.charAt(3))
console.log(str.indexOf('an',4))
console.log(str.concat(' october 2'))
console.log(str.includes('jay',3))
console.log(str.replace('thi','gg'))
console.log(str.split('a',3))
console.log(str.substr(2,7))
console.log(str.search('an'))
console.log(str.trim())
console.log('=============================')
let string='golgoppa'
console.log(string.toLowerCase())
console.log(string.toUpperCase())
console.log(string.charAt(4))
console.log(string.indexOf('op',3))
console.log(string.concat(' spicy'))
console.log(string.includes('opp',2))
console.log(string.replace('o','rr'))
console.log(string.split('o',1))
console.log(string.substr(3,6))
console.log(string.search('pp'))
console.log(string.trim())
console.log('=============================')
let rd='biriyani'
console.log(rd.toLowerCase())
console.log(rd.toUpperCase())
console.log(rd.charAt(2))
console.log(rd.indexOf('ya',3))
console.log(rd.concat(' veg'))
console.log(rd.includes('ri',5))
console.log(rd.replace('i','nn'))
console.log(rd.split('i',2))
console.log(rd.substr(4,6))
console.log(rd.search('yan'))
console.log(rd.trim())
console.log('=============================')
let island='Andaman Nicobar'
console.log(island.toLowerCase())
console.log(island.toUpperCase())
console.log(island.charAt(8))
console.log(island.indexOf('man',3))
console.log(island.concat(' sihcb'))
console.log(island.includes('cob',5))
console.log(island.replace('d','rr'))
console.log(island.split('a',2))
console.log(island.substr(4,8))
console.log(island.search('bar'))
console.log(island.trim())
console.log('=============================')
